const productImageOverrides: Record<string, string> = {
  "cl-01": "/legacy/products/cl-01.jpg",
  "cl-02": "/legacy/products/cl-02.jpg",
  "cl-03": "/legacy/products/cl-03.jpg",
  "cl-04": "/legacy/products/cl-04.jpg",
  "cl-05": "/legacy/products/cl-05.jpg",
  "cl-06": "/legacy/products/cl-06.jpg",
  "cl-07": "/legacy/products/cl-07.jpg",
  "cl-08": "/legacy/products/cl-08.jpg",
  "cl-09": "/legacy/products/cl-09.jpg",
  "cl-10": "/legacy/products/cl-10.jpg",
  "cl-11": "/legacy/products/cl-11.jpg",
  "cl-12": "/legacy/products/cl-12.jpg",
  "cl-13": "/legacy/products/cl-13.jpg",
  "cl-14": "/legacy/products/cl-14.jpg",
  "cl-15": "/legacy/products/cl-15.jpg",
  "cl-16": "/legacy/products/cl-16.jpg",
  "cl-g1": "/legacy/products/cl-g1.jpg",
  "cl-g2": "/legacy/products/cl-g2.jpg",
  "cl-g3": "/legacy/products/cl-g3.jpg",
  "cl-g4": "/legacy/products/cl-g4.jpg",
  "cl-g5": "/legacy/products/cl-g5.jpg",
  "av-01": "/legacy/products/av-01.png",
  "av-02": "/legacy/products/av-02.png",
  "av-03": "/legacy/products/av-03.jpg",
  "sm-01": "/legacy/products/sm-01.png",
  "sm-02": "/legacy/products/sm-02.png",
  "sm-03": "/legacy/products/sm-03.png",
  "sm-04": "/legacy/products/sm-04.png",
  "sm-05": "/legacy/products/sm-05.png",
  "sm-06": "/legacy/products/sm-06.png",
  "sm-07": "/legacy/products/sm-07.png",
  "sm-08": "/legacy/products/sm-08.png",
  "sm-09": "/legacy/products/sm-09.png",
  "sm-10": "/legacy/products/sm-10.png",
  "sm-11": "/legacy/products/sm-11.png",
  "sm-12": "/legacy/products/sm-12.png",
  "sm-13": "/legacy/products/sm-13.png",
  "sm-14": "/legacy/products/sm-14.png",
  "sm-15": "/legacy/products/sm-15.png",
  "sm-16": "/legacy/products/sm-16.png",
  "sm-g1": "/legacy/products/sm-g1.png",
  "sm-g2": "/legacy/products/sm-g2.png",
  "sm-g3": "/legacy/products/sm-g3.png",
  "sm-g4": "/legacy/products/sm-g4.png",
  "sm-g5": "/legacy/products/sm-g5.png",
  "sm-g6": "/legacy/products/sm-g6.png",
};

export function getProductImageOverride(colorId: string, fallback: string) {
  return productImageOverrides[colorId] ?? fallback;
}
